// STYLES

// DEV IMPORTS
import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router'

// COMPONENTS
import FeaturedArticle from "../components/categoryPage/FeaturedArticle";
import PopularTalk from "../components/categoryPage/PopularTalk";
import RecentPost from "../components/RecentPost";

// FUNCTIONS
import {
  getFeaturedPost,
  getFiveLatestPostGeneral,
  getPopularTalk,
} from "../lib/talkToGhost";

export default function Home(props) {
  //shoptalk

  //console.log(props.featuredPost);
  //console.log(props.recentPost);
  //console.log(props.popularTalk);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedArticle featuredPost={props.featuredPost} />
      <PopularTalk popularTalk={props.popularTalk} />
      <RecentPost recentPost={props.recentPost} />
    </>
  );
}

export async function getStaticProps(context) {
  const featuredPost = await getFeaturedPost();
  const recentPost = await getFiveLatestPostGeneral();
  const popularTalk = await getPopularTalk();

  //Build fallback to display most recent if none are featured

  // if (!posts) {
  //   return {
  //     notFound: true,
  //   };
  // }

  return {
    props: { featuredPost, recentPost, popularTalk },
  };
}
